image: python:3.10
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
cache:
  paths:
    - .cache/pip
    - venv/
before_script:
  - pip install pytest
  - pip install pandas
test:
  script:
    - python -m pytest













