image: python:3.10
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
cache:
  paths:
    - .cache/pip
    - venv/
before_script:
  - apt-get update && apt-get install -y python3-opencv
  - pip install pytest pandas geopandas rasterio rtree pygeos opencv-python pillow matplotlib tensorflow_hub tensorflow keras scikit-learn
test:
  script:
    - python -m pytest













